---
abstract: 'a fluent numeric interface'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Numbers
provides:
  Acme::Numbers:
    file: lib/Acme/Numbers.pm
    version: 1.2
requires:
  Lingua::EN::Words2Nums: 0
  Test::More: 0.62
resources:
  license: http://dev.perl.org/licenses/
version: 1.2
